//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатуры.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатуры CustomAttributes)

    // *** End programmer edit section *** (Номенклатуры CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатурыE", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "ЕдИзмер as \'Единицы измерения\'",
            "ЕдИзмер.ЕдИзмер as \'Единица измерения\'"}, Hidden=new string[] {
            "ЕдИзмер.ЕдИзмер"})]
    [MasterViewDefineAttribute("НоменклатурыE", "ЕдИзмер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЕдИзмер")]
    [View("НоменклатурыL", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "ЕдИзмер.ЕдИзмер as \'Ед измер\'"})]
    public class Номенклатуры : ICSSoft.STORMNET.DataObject
    {
        
        private string fНоменклатура;
        
        private IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf.ЕдИзмер fЕдИзмер;
        
        // *** Start programmer edit section *** (Номенклатуры CustomMembers)

        // *** End programmer edit section *** (Номенклатуры CustomMembers)

        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатуры.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Номенклатуры.Номенклатура CustomAttributes)
        [StrLen(255)]
        public virtual string Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатуры.Номенклатура Get start)

                // *** End programmer edit section *** (Номенклатуры.Номенклатура Get start)
                string result = this.fНоменклатура;
                // *** Start programmer edit section *** (Номенклатуры.Номенклатура Get end)

                // *** End programmer edit section *** (Номенклатуры.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатуры.Номенклатура Set start)

                // *** End programmer edit section *** (Номенклатуры.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Номенклатуры.Номенклатура Set end)

                // *** End programmer edit section *** (Номенклатуры.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Номенклатуры.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатуры.ЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (Номенклатуры.ЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмер"})]
        [NotNull()]
        public virtual IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf.ЕдИзмер ЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатуры.ЕдИзмер Get start)

                // *** End programmer edit section *** (Номенклатуры.ЕдИзмер Get start)
                IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf.ЕдИзмер result = this.fЕдИзмер;
                // *** Start programmer edit section *** (Номенклатуры.ЕдИзмер Get end)

                // *** End programmer edit section *** (Номенклатуры.ЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатуры.ЕдИзмер Set start)

                // *** End programmer edit section *** (Номенклатуры.ЕдИзмер Set start)
                this.fЕдИзмер = value;
                // *** Start programmer edit section *** (Номенклатуры.ЕдИзмер Set end)

                // *** End programmer edit section *** (Номенклатуры.ЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатурыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатурыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатурыE", typeof(IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf.Номенклатуры));
                }
            }
            
            /// <summary>
            /// "НоменклатурыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатурыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатурыL", typeof(IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf.Номенклатуры));
                }
            }
        }
    }
}
