//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние отгрузки.
    /// </summary>
    // *** Start programmer edit section *** (СостОгрузки CustomAttributes)

    // *** End programmer edit section *** (СостОгрузки CustomAttributes)
    public enum СостОгрузки
    {
        
        // *** Start programmer edit section *** (СостОгрузки.Отгруж CustomAttributes)

        // *** End programmer edit section *** (СостОгрузки.Отгруж CustomAttributes)
        [Caption("Отгружен")]
        Отгруж,
        
        // *** Start programmer edit section *** (СостОгрузки.НеОтгруж CustomAttributes)

        // *** End programmer edit section *** (СостОгрузки.НеОтгруж CustomAttributes)
        [Caption("Не отгружен")]
        НеОтгруж,
        
        // *** Start programmer edit section *** (СостОгрузки.ЧастичОтгруз CustomAttributes)

        // *** End programmer edit section *** (СостОгрузки.ЧастичОтгруз CustomAttributes)
        [Caption("Частично отгружен")]
        ЧастичОтгруз,
    }
}
